export const UPDATE_CURRENCIES: string = "UPDATE_CURRENCIES";
export const UPDATE_CURRENCIES_FAILED: string = "UPDATE_CURRENCIES_FAILED";
export const UPDATE_CURRENCIES_SUCCESS: string = "UPDATE_CURRENCIES_SUCCEESS";
export const FETCH_CURRENCIES: string = "FETCH_CURRENCIES";
